name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

     
      
      - name: Build and push user
        uses: docker/build-push-action@v2
        with:
          context: ./user
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user:latest
        
      - name: Build and push product
        uses: docker/build-push-action@v2
        with:
          context: ./product
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product:latest
      
      - name: Build and push order
        uses: docker/build-push-action@v2
        with:
          context: ./admin
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/admin:latest

          - name: Build and push order
        uses: docker/build-push-action@v2
        with:
          context: ./cart-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cart-service:latest